### PR TITLE
fix(playground): fix importing definition from URL

### PR DESCRIPTION
**Pull request by rainum**
### Description
 This PR fixed an issue when after importing the file content is missing. The only thing that is displayed is the string [object ArrayBuffer].

### How Has This Been Tested?

Locally.

### Screenshots (if appropriate):

https://github.com/user-attachments/assets/3e130e8b-7b5e-46c4-a7bd-8f605cd3f072

### My PR contains...

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [x] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by char0n** [comment]
Thanks @rainum. Do you think it would make sense to use `File` interface from `apidom-reference` package to abstract the conversion? 

```js
new String(File({ uri, data }));
```
or
```js
new File({ uri, data }).toString()
```

**Comment by char0n** [comment]
@rainum I've changed the title of the PR to `fix(playground): fix importing definition from URL`. We use conventional commit spec to guide you with commit messages. In top of that we have a convention that commit message SHOULD start with `verb` in imperative form.

**Comment by rainum** [comment]
> Thanks @rainum. Do you think it would make sense to use `File` interface from `apidom-reference` package to abstract the conversion?
> 
> ```js
> new String(File({ uri, data }));
> ```
> 
> or
> 
> ```js
> new File({ uri, data }).toString()
> ```

I like the idea 👍 Let me check if it fits well

**Comment by char0n** [comment]
Squash + merge is a preferred way to get the PR into trunk.

**Review by char0n — APPROVED** [review]
LGTM, nice work!

**Pull request merged**
